import Head from "next/head";
import Playlist from "../../components/Playlist";

export default function playlist() {
  return (
    <>
      <Head>
        <title>playlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Playlist />
    </>
  );
}
