import Head from "next/head";

export default function home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-cyan-400">Tailwind Setup success 🚀 </h1>
    </>
  );
}
