import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Player from "../common/Player";
import Sidebar from "../common/Sidebar";
import Home from "../components/Home";

export default function home() {
  const router = useRouter();
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Home />
    </>
  );
}
