import Head from "next/head";
import Player from "../../common/Player";
import Sidebar from "../../common/Sidebar";
import Album from "../../components/Album";

export default function album() {
  return (
    <div className="page">
      <Head>
        <title>album</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      <Album />
      <Player />
    </div>
  );
}
