export const GET_FEATURED_PLAYLIST_START = "GET_FEATURED_PLAYLIST_START";
export const GET_FEATURED_PLAYLIST_SUCCESS = "GET_FEATURED_PLAYLIST_SUCCESS";
export const GET_FEATURED_PLAYLIST_FAILURE = "GET_FEATURED_PLAYLIST_FAILURE";
export const GET_FEATURED_PLAYLIST_END = "GET_FEATURED_PLAYLIST_END";

export const GET_PLAYLIST_START = "GET_PLAYLIST_START";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";
export const GET_PLAYLIST_FAILURE = "GET_PLAYLIST_FAILURE";
export const GET_PLAYLIST_END = "GET_PLAYLIST_END";
